### ISSUE TITLE
Create ability for delayed response:

### ISSUE THREAD

**Issue by campfire5** [lomsa-dev/http-mock-adapter#106]
Create ability for delayed response:

Current vision for interface:

```dart
dio..onGet("path", 
     (request){}, 
    delay: Duration(seconds:1),
)

```

In `DioAdapter` or `DiopInterceptor` delay param will be checked for `null` if it is null adapter will respond normally, if not it will respond with specified `delay`

**Comment by LukaGiorgadze** [comment]
I would say `timeout` rather `delay`

**Comment by campfire5** [comment]
> I would say `timeout` rather `delay`

`Timeout` is more like when request times out and you get no response.
`Delay` represents the time between request and response.

e.g sentences:
"`Response` was delayed but arrived after 3 seconds"
"`Request` has timed out after 3 seconds"

**Comment by GiorgiBeriashvili** [comment]
Closing due to #109
