### ISSUE TITLE
Mocking non-JSON response

### ISSUE THREAD

**Issue by dricholm** [lomsa-dev/http-mock-adapter#107]
## Description

For my current use case I need to mock a response for an `application/xml` content response. But since the mocked response body is always passed to `jsonEncode()` in `RequesHandler` the body will be surrounded with `"`s, while existing ones will be escaped to `\"`.

## Steps to reproduce

1. Mock a response body with a `String` data.
2. Verify that actual response is equal to mocked data.

A simple test to reproduce:
```dart
void main() {
  final dioAdapter = DioAdapter();
  final dio = Dio()..httpClientAdapter = dioAdapter;

  test('should not encode body with jsonEncode', () async {
    const expected = '<xml xmlns="http://www.w3.org/2005/Atom">Test</xml>';
    dioAdapter.onGet(
      '/',
      (request) => request.reply(
        200,
        expected,
        headers: {
          Headers.contentTypeHeader: ['application/xml'],
        },
      ),
    );

    final response = await dio.get<String>(
      '/',
      options: Options(
        responseType: ResponseType.plain,
      ),
    );

    expect(response.data, expected);
  });
}
```

## Expected behavior

Response body is not encoded, remains as plain string.

## Screenshots

Screenshot of the above test result.
![image](https://user-images.githubusercontent.com/32329112/119826945-dfbffc00-bef8-11eb-8393-a66c63c99c6c.png)

## System details

OS: Windows 10
Flutter 2.2.0 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b22742018b (12 days ago) • 2021-05-14 19:12:57 -0700
Engine • revision a9d88a4d18
Tools • Dart 2.13.0

## Additional context

The fix should probably be to conditionally apply `jsonEncode()` depending on the header type given. Current implementation has a default header that contains `Headers.jsonContentType`.
Maybe something similar to this in `request_handler.dart`?

```dart
final isJson =
      headers[Headers.contentTypeHeader]?.contains(Headers.jsonContentType) ??
          false;

  requestMap[this.statusCode] = () => AdapterResponse.from(
        isJson ? jsonEncode(data) : data,
        this.statusCode,
        headers: headers,
        statusMessage: statusMessage,
        isRedirect: isRedirect,
      );
```
This will make the above test pass.

I also noticed the `request_handler.dart` doesn't have any tests. so if something like my proposal would be okay I could also open a PR for it. Please let me know what you think/any changes could be applied.

**Comment by GiorgiBeriashvili** [comment]
Thank you for very detailed and relevant issue!

I will assign it to myself and I will try to fix it as soon as I can.

**Comment by GiorgiBeriashvili** [comment]
@dricholm I looked at the problem and your offered solution. I think that it solves it quite nicely. `Dio` uses JSON a lot, thus why we had JSON by default, but of course, it should not be a necessity.

> I also noticed the request_handler.dart doesn't have any tests. so if something like my proposal would be okay I could also open a PR for it. Please let me know what you think/any changes could be applied.

I would encourage you to do so! You came up with the solution and you might as well take credit for it. I cannot think of any additional changes, I think specific handling of JSON and plain text for any other cases is enough, at least for now.

**Comment by dricholm** [comment]
@GiorgiBeriashvili Thank you for your answer and friendly attitude!
I just opened a PR for this, please let me know if there's anything I missed and should change.

**Comment by GiorgiBeriashvili** [comment]
I will close the issue as it seems to be resolved, thanks to you, @dricholm!
