### ISSUE TITLE
Mocking Post with FormData

### ISSUE THREAD

**Issue by ComplexCarbos** [lomsa-dev/http-mock-adapter#111]
## Description

I've been unable to mock a Post that sends FormData. Try as I might, I can't setup the route correctly:

`Assertion failed: "Could not find mocked route matching request for https://example.com/POST/Instance of 'FormData'/{}/{content-type: multipart/form-data; boundary=--dio-boundary-4160721626, content-length: 173}"`

Simplified, the method I'm trying to test looks like something this:

```
  Future<void> postSomething(
      {required String url, required FormData formData}) async {
    try {
      final response = await _httpClient.post(url, data: formData);
      if (response.statusCode != 200) {
        print('Request failed ${response.statusCode}');
      }
    } on DioError catch (e) {
      print(e.message);
      print(e.type);

      if (e.type == DioErrorType.connectTimeout ||
          e.type == DioErrorType.receiveTimeout) {
        print('Doing something cool with a timeout error');
        throw Exception('TIMEOUT');
      } else {
        print('Doing something cool with unexepcted error');
      }
    }
  }
```

The current iteration of my test looks like:

```
    test('postSomething', () {
      final errorToThrow = DioError(
          requestOptions: RequestOptions(path: path),
          type: DioErrorType.receiveTimeout,
          response: Response(
            statusCode: 408,
            requestOptions: RequestOptions(path: path),
          ),
          error: {'message': 'Timeout'});

      print('Form Length: ${formData.length}');
      print('Form Boundary: ${formData.boundary}');

      dioAdapter.onPost(path, (request) => request.throws(408, errorToThrow),
          data: formData);

      final postService = PostService(httpClient: dio);

      expect(
        () async =>
            await postService.postSomething(url: path, formData: formData),
        throwsA(
          predicate(
            (e) => e is Exception && e.toString().startsWith('TIMEOUT'),
          ),
        ),
      );
    });
```
## Steps to reproduce

Working example here: https://github.com/ComplexCarbos/dio_mock_example

## Expected behavior

Can Mock a Post request that takes FormData as a parameter.

**Comment by jscti** [comment]
`data` expects the exact same object.

Ir bypassed that by usind `data: Matchers.any`

**Comment by ComplexCarbos** [comment]
Thank you for the note - its much appreciated!

I might be missing something obvious because Matchers.any isn't working for me. I downloaded the source code and updated example/main.dart with a basic test that looks like this:

```
    test('My Test', () async {
      const route = '/signup';

      final multipartFile = MultipartFile.fromBytes(
        [123, 456],
        filename: 'file',
      );

      final formData = FormData.fromMap({'file': multipartFile});

      dioAdapter.onPost(
          route,
          (request) => request.throws(
                401,
                DioError(
                  requestOptions: RequestOptions(
                    path: route,
                  ),
                ),
              ),
          data: Matchers.any,

      await dio.post(route, data: formData);
    });
```

The existing tests all pass. The one I added fails with same error I reported earlier:


`Could not find mocked route matching request for POST /signup { data: Instance of 'FormData', query parameters: {}, headers: {content-type: multipart/form-data; boundary=--dio-boundary-2175753315, content-length: 168} }`

When I step through the code, I see it matches the route and the data, but is failing on the first header (content-type) on line 90 of matches_request.dart.

**Comment by kuhnroyal** [comment]
You need to use the `FormDataMatcher` like so:

```dart
      final formData = FormData.fromMap({'file': multipartFile});

      dioAdapter.onPost(
          route,
          (request) => request.throws(
                401,
                DioError(
                  requestOptions: RequestOptions(
                    path: route,
                  ),
                ),
              ),
          data: Matchers.formData(formData),
      );
      await dio.post(route, data: formData);
```

**Comment by kuhnroyal** [comment]
I have https://github.com/kuhnroyal/http-mock-adapter/commit/49f9e39076ad690ba0409010630528777dfbe645 ready to wrap the FormData automatically in a matcher.

**Comment by ComplexCarbos** [comment]
I did try FormDataMatcher and couldn't get it to work - the matching logic appears to fail when comparing the headers. For example, printing headers and request headers:

```
{content-type: multipart/form-data; boundary=--dio-boundary-0779527207, content-length: 168}
{content-type: application/json; charset=utf-8, content-length: IntegerMatcher { strict: false }}
```

However, after playing around some more I found the matching logic will return true if matchers are specified for the headers as well.

This seems to work:

```
test('My Test', () async {
  const route = '/signup';

  final multipartFile = MultipartFile.fromBytes(
    [123, 456],
    filename: 'file',
  );

  final headers = <String, dynamic>{
    'content-type': Matchers.any,
    'content-length': Matchers.any
  };

  final formData = FormData.fromMap({'file': multipartFile});

  dioAdapter.onPost(
      route,
      (request) => request.throws(
            401,
            DioError(
              type: DioErrorType.receiveTimeout,
              requestOptions: RequestOptions(
                path: route,
              ),
            ),
          ),
      data: Matchers.formData(formData),
      headers: headers);

  expect(
    () async => await dio.post(route, data: formData),
    throwsA(predicate(
        (e) => e is DioError && e.type == DioErrorType.receiveTimeout)),
  );
});
```

I really appreciate the help and tips.

Thank you!

**Comment by kuhnroyal** [comment]
> ```
> {content-type: multipart/form-data; boundary=--dio-boundary-0779527207, content-length: 168}
> {content-type: application/json; charset=utf-8, content-length: IntegerMatcher { strict: false }}
> ```

Yea this seems wrong, the default matcher for the `content-type` must not be added on every request. I also changed this to some smarter handling in https://github.com/lomsa-dev/http-mock-adapter/pull/118 but `multipart/form-data` may still fail, need to check this out.

The default matcher is only added if you don't have a custom matcher for the `content-length` header. When you added `Matchers.any`, the default matcher is no longer used. You can also try something like `Matchers.pattern('multipart/form-data; boundary.*')`.
