### ISSUE TITLE
Refactoring the External API and adding a Matcher API

### ISSUE THREAD

**Issue by humblerookie** [lomsa-dev/http-mock-adapter#124]
## Description

1) So the external api provided by MockAdapter is essentially inverting the dependency graph i.e.

```dart
final dio = Dio(BaseOptions());
final dioAdapter = DioAdapter(dio: dio);
```
Here the adapter is  forced to  be responsible for setting itself as the httpclientadapter. This creates a few issues while using DI libraries one of which is Dio needs to be instantiated before the adapter despite the adapter not depending of the Dio instance.

it would be great if instead the task of setting the adapter is externalized i.e.
```dart
final dio = Dio(BaseOptions());
final dioAdapter = DioAdapter();
dio.httpClientAdapter = dioAdapter;
```

2) DioAdapter relies on an internal request matching logic which essentially relies on the entire signature to be equal. Sometimes we may desire the request matching  to be simpler like say just consider `path` and not the entire request including headers etc.
Current implementation can be improved by externalising `matching`

We can have an external interface like this
```dart
abstract class HttpRequestMatcher{
  
  bool matches(RequestOptions ongoingRequest, Request matcher);
}

```
and supplemented by passing an instance to the adapter like this
```dart
class DioAdapter extends HttpClientAdapter with Recording, RequestHandling {

  @override
  final HttpRequestMatcher matcher;

  DioAdapter({
    required this.matcher,
  });
```

This would allow us to have a few matchers like this prebaked into the library and let the users create their own custom matchers as well.
```dart
class UrlPathMatcher implements HttpRequestMatcher{

  @override
  bool matches(RequestOptions ongoingRequest, Request matcher) {
    return doesRouteMatch(ongoingRequest.path, matcher.route);
  }
}
```

Happy to hear your thoughts on this.

**Comment by theiskaa** [comment]
Resolved by: #125
