### ISSUE TITLE
can i request to onDownload when add unit test ?

### ISSUE THREAD

**Issue by anggadwi16** [lomsa-dev/http-mock-adapter#137]
## Guidelines for a feature request

- [ ] **Is your feature request related to a problem? Please describe.** A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
- [ ] **Describe the solution you'd like.** A clear and concise description of what you want to happen.
- [ ] **Describe alternatives you've considered.** A clear and concise description of any alternative solutions or features you've considered.
- [ ] **Additional context.** Add any other context or screenshots about the feature request here.

**Tip**: Delete everything but the following section that contains the description of the feature request.

---

## Description

Please describe your feature request.

Thank you!

**Comment by LukaGiorgadze** [comment]
Hi @anggadwi16 , can you describe what does `onDownload` mean and what should you expect from that?
Thank you!

**Comment by LukaGiorgadze** [comment]
Closed due to inactivity
