### ISSUE TITLE
[v0.4.0] collection version conflict between the v0.4.0 and flutter_test

### ISSUE THREAD

**Issue by chunghha** [lomsa-dev/http-mock-adapter#141]
## Description

While installing the v0.4.0 I am getting this error:

```
Because http_mock_adapter >=0.4.0 depends on collection ^1.17.1 and every version of flutter_test from sdk depends on collection 1.17.0, http_mock_adapter >=0.4.0 is incompatible with flutter_test from sdk.
So, because adapter depends on both flutter_test from sdk and http_mock_adapter ^0.4.0, version solving failed.
```

## Steps to reproduce

Just updated the http_mock_adapter version from v0.3.3 to v0.4.0. Run "flutter pub upgrade"

## Expected behavior

No failure on resolving dependencies.

## System details

Flutter version 3.7.3 on channel stable
Dart version 2.19.2

## Additional context

Probably the v0.4.0 needs to lower down the collection package version to ^1.17.0.

**Comment by chunghha** [comment]
Meanwhile I can use 'dependency_overrides' to my troublesome projects' pubspec.yaml.

dependency_overrides:
  collection: "1.17.1"

**Comment by LukaGiorgadze** [comment]
@chunghha Could you try to update [test](https://pub.dev/packages/test/versions) to the latest version in your pubspec?

**Comment by kuhnroyal** [comment]
@LukaGiorgadze we explicitly tried to avoid this version bump of collection in the Dio upgrade branch

**Comment by chunghha** [comment]
@LukaGiorgadze I believe typically projects have this set with "flutter_test" as the below which uses collection. 

flutter_test:
    sdk: flutter

That means collection version from sdk should be set with http_mock_adapter. 

I set my projects with minimum sdk version 2.19.0 so collection 1.17.0 matches with. If someone else wants a. lower minimum sdk version then probably setting the collection version to 1.15.0 is the safe bet as @kuhnroyal pointed in the review of dio v5 PR.

https://pub.dev/packages/collection/changelog

**Comment by kuhnroyal** [comment]
Yes the problem is that flutter enforces a certain `collection` version. Stable (Flutter 3.7) is on `collection: 1.16.0` but if you want some form of backward compatibility then the library should target `1.15.0`.

**Comment by LukaGiorgadze** [comment]
@chunghha @kuhnroyal 
According to Flutter's official Github, it seems that they have an updated version of the collection (1.7.1).
https://github.com/flutter/flutter/blob/master/packages/flutter_test/pubspec.yaml#L35

Could you try `flutter update-packages` ?

I'm okay to revert it back, but I want to make sure that you have guys the latest versions of flutter + packages that depend on the collection.

**Comment by chunghha** [comment]
I concur with what @kuhnroyal wrote about the backward compatibility. 

I have the latest Flutter stable sdk version 3.7.3 installed,  so with flutter_test from the sdk version, collection 1.7.0 is installed for my project. Then I got to override the version to 1.7.1 in the pubspec.yaml  in order for me to install http_mock_adapter 0.4.0 because it requires the 1.7.1.

**Comment by LukaGiorgadze** [comment]
I guess downgrading to 1.16.0 can solve that problem so there won't be any incompatibility. How does it sound? @chunghha @kuhnroyal

**Comment by LukaGiorgadze** [comment]
Take a look at https://github.com/lomsa-dev/http-mock-adapter/pull/142
