### ISSUE TITLE
http_mock_adapter 0.5.0 conflicts with flutter_test collection version.

### ISSUE THREAD

**Issue by quoc-huynh-cosee** [lomsa-dev/http-mock-adapter#155]
## Description

I'm receiving this error when I trying to use the new version of http_mock_adapter. This is due that the flutter stable version is still using a lower collection version than 1.18.0.

```
Because http_mock_adapter >=0.5.0 depends on collection ^1.18.0 and every version of flutter_test from sdk depends on collection 1.17.1, http_mock_adapter >=0.5.0 is incompatible with flutter_test from sdk.
So, because myapp depends on both flutter_test from sdk and http_mock_adapter ^0.5.0, version solving failed.
```

## Steps to reproduce

1. Create a new project (Flutter stable)
2. Add flutter_test & http_mock_adapter 0.5.0 to pubspec.yaml.
3. Run flutter pub get

## Expected behavior

The shouldn't be an error.

**Comment by LukaGiorgadze** [comment]
Hi @quoc-huynh-cosee, 
This is a known issue https://github.com/lomsa-dev/http-mock-adapter/issues/141
One way to fix it is to not update `http-mock-adapter` and stick with [v0.4.4](https://github.com/lomsa-dev/http-mock-adapter/releases/tag/v0.4.4).

The current stable version of Flutter depends on 1.18 collection https://github.com/search?q=repo%3Aflutter%2Fflutter+collection%3A&type=code which should not be a problem.

Could you try to upgrade your Flutter?

**Comment by LukaGiorgadze** [comment]
@quoc-huynh-cosee yeah, it seems it's still far away from the stable version.
Okay, I'll downgrade to 1.17.2

**Comment by quoc-huynh-cosee** [comment]
@LukaGiorgadze Thanks!

**Comment by LukaGiorgadze** [comment]
@quoc-huynh-cosee We are preparing 0.6.0 release and collection 1.17.1 will be there.

It's in the main branch https://github.com/lomsa-dev/http-mock-adapter/commit/4a16952c9558775d2f4df6ad60d3f26a10080f82

**Comment by sebastianbuechler** [comment]
@LukaGiorgadze Do you want to do the release? I think #161 won't be applicable before adhering to the commit structure anyway.

**Comment by LukaGiorgadze** [comment]
@sebastianbuechler Yeh, agree, I just did not have time to write a new doc and update README according your PRs 😮‍💨 I hope to do it tomorrow.

**Comment by LukaGiorgadze** [comment]
@quoc-huynh-cosee v0.6.0 version has been released. Hope it fixes your issue.
