### ISSUE TITLE
Support multiple platforms (pub.dev)

### ISSUE THREAD

**Issue by GiorgiBeriashvili** [lomsa-dev/http-mock-adapter#72]
## Description

The [score](https://pub.dev/packages/http_mock_adapter/score) of the package is not maximum due to an issue regarding multi-platform support.

The issue is described as:

<details>
  <summary>
    Package not compatible with runtime js
  </summary>
  <br/>
  Because:
  <br/>
  <ul>
    <li><code>package:http_mock_adapter/http_mock_adapter.dart</code> that imports:</li>
    <li><code>package:http_mock_adapter/src/adapters/dio_adapter.dart</code> that imports:</li>
    <li><code>package:dio/adapter.dart</code> that imports:</li>
    <li><code>package:dio/src/adapters/io_adapter.dart</code> that imports:</li>
    <li><code>dart:io</code></li>
  </ul>
</details>

The traced information depicts that [Dio](https://github.com/flutterchina/dio) uses `dart:io` package in its source code, which is not compatible with JavaScript runtime (Meaning that `Dio` is not completely compatible for web usage).

The problem may be solved by [conditional importing](https://dart.dev/guides/libraries/create-library-packages#conditionally-importing-and-exporting-library-files), [universal_io](https://pub.dev/packages/universal_io) or other method.

The issue in the context of `http-mock-adapter` will be pertinent until `Dio` fixes the issue.

**Tip**: Use [pana](https://pub.dev/help/scoring#calculating-pub-points-prior-to-publishing) to calculate package's score locally.

**Comment by campfire5** [comment]
This should be opened on the repo of Dio itself.

**Comment by GiorgiBeriashvili** [comment]
@campfire5 If you mean to open an issue for [Dio](https://github.com/flutterchina/dio) in addition to having this issue open until `http-mock-adapter` will not be affected by the problem, I agree.

**Comment by campfire5** [comment]
Yep, it's actually Dio's error not ours.

**Comment by GiorgiBeriashvili** [comment]
@campfire5 It is, though it still remains an issue on our end while the problem remains, that's why I tried to be more specific.

I understand that the issue's description might not have been clear about this, thus I will edit it for better clarity.

**Comment by campfire5** [comment]
I was just bored mention it, It really does not make a big difference if it is opened here on http mock adapter or not

**Comment by GiorgiBeriashvili** [comment]
This issue will most likely be resolved by #83

**Comment by GiorgiBeriashvili** [comment]
Resolved as a result of #115
