### ISSUE TITLE
Add queryParameters to option to adapter RequestHandler factory methods

### ISSUE THREAD

**Issue by nishtahir** [lomsa-dev/http-mock-adapter#75]
## Description

There doesn't seem to be an [option](https://github.com/lomsa-dev/http-mock-adapter/blob/adda8fbf35e796aa6462536dfbe2cb998df0ba1f/lib/src/request.dart#L220) to match against query parameters while using request handlers.
I tried adding the param to the URL string,

```
dioAdapter.onGet('/search?param=$query')
``` 

However, this doesn't seem to match requests correctly. 
Using the `onRoute` API does work for this use case but it's a lot more verbose.

```
dioAdapter
  .onRoute(
    '/search',
    request: Request(
      route: '/search',
      method: RequestMethods.GET,
      headers: {'authorization': 'Bearer $token'},
      queryParameters: {
        'param': 'query',
      },
    ),
  );
```

It would be nice to expose an API for this on the factory methods.

**Comment by campfire5** [comment]
Can you try this ?
```
dioAdapter
  .onGet(
    '/search',
    request: Request(
      headers: {'authorization': 'Bearer $token'},
      queryParameters: {
        'param': 'query',
      },
    ),
  );
```

**Comment by nishtahir** [comment]
> Can you try this ?
> 
> ```
> dioAdapter
>   .onGet(
>     '/search',
>     request: Request(
>       headers: {'authorization': 'Bearer $token'},
>       queryParameters: {
>         'param': 'query',
>       },
>     ),
>   );
> ```

Doesn't seem to be working for me. As of version 0.1.5, this doesn't seem to be an [API](https://github.com/lomsa-dev/http-mock-adapter/blob/b01ddae094d41422e498ca9e6277f167c4443e9c/lib/src/request.dart#L213) that exists?

**Comment by campfire5** [comment]
Okay, I will take a better look, thank you for your time.

**Comment by alexshikov** [comment]
We've faced the same use case. Would be nice to have this feature.

**Comment by GiorgiBeriashvili** [comment]
#84 attempts to solve this issue.

An [excerpt](https://github.com/lomsa-dev/http-mock-adapter/blob/65734a50a29802f2dddb20d8f5ef7b8dd490f7f3/test/adapters/dio_adapter_test.dart#L128) from the changes for demonstration:

```dart
      test('mocks requests with query parameters', () async {
        const books = [
          {'name': 'First Book'},
          {'name': 'Second Book'},
        ];

        dioAdapter.onGet(
          '/search',
          (request) => request.reply(200, books),
          queryParameters: {'query': 'book'},
        );

        response = await dio.get(
          '/search',
          queryParameters: {'query': 'book'},
        );

        expect(books, response.data);
      });
```

Please let me know if this is suitable for your use cases.

**Comment by GiorgiBeriashvili** [comment]
#84 has been merged and it resolves the issue regarding query parameters, therefore I will close this issue.
