### ISSUE TITLE
Allow to ignore headers by name when trying to match a request

### ISSUE THREAD

**Issue by kuhnroyal** [lomsa-dev/http-mock-adapter#80]
## Description

When changing POST request content in a test I always have to update the content-length header to match the new length.
To make this easier, I would like to ignore some headers when requests are matched.

This could be solved with a complex request matching implementation (like https://github.com/lomsa-dev/http-mock-adapter/issues/68) which I would really love to see.

**Comment by kuhnroyal** [comment]
Nevermind, the headers don't seem to be part of the matching. Was another random error.

**Comment by kuhnroyal** [comment]
Have to re-open this, after my changes in #82 it is now clear that the headers are part of the signature that is matched.

**Comment by GiorgiBeriashvili** [comment]
@kuhnroyal If I understood correctly, might a solution such as [this](https://github.com/lomsa-dev/http-mock-adapter/blob/adda8fbf35e796aa6462536dfbe2cb998df0ba1f/test/matches_request_test.dart#L203) be applicable in this case?

It is not ignoring in a straightforward sense but more in indirect way, as it will accept any type of `content-length`.

**Comment by kuhnroyal** [comment]
That looks promising, have to admit that I have not dug into the matchers yet.

**Comment by GiorgiBeriashvili** [comment]
> That looks promising, have to admit that I have not dug into the matchers yet.

You can see the changes here #69

If you deem the `Matcher` implementation to be relevant and helpful in this case, perhaps we could resolve the issue.

**Comment by kuhnroyal** [comment]
Perfect, ignoring may be relevant for some other cases but for me this enough at the moment.
