### ISSUE TITLE
Upgrade dependencies to the newest ones

### ISSUE THREAD

**Issue by mihailmerkov** [lomsa-dev/http-mock-adapter#86]
Hi, could you please update your dependencies to the newest ones, because the projects migrated to flutter 2 are quite affected?

**Comment by kuhnroyal** [comment]
You can try using it directly from https://github.com/lomsa-dev/http-mock-adapter/pull/83

**Comment by simonsankar** [comment]
@kuhnroyal How can I reference that branch in the pubspec?

**Comment by LukaGiorgadze** [comment]
@mihailmerkov Can we close this issue?

cc: @GiorgiBeriashvili

**Comment by GiorgiBeriashvili** [comment]
> @mihailmerkov Can we close this issue?
> 
> cc: @GiorgiBeriashvili

I was awaiting for confirmation by @mihailmerkov, but yes, the issue should no longer be prevalent and can be closed.
