### ISSUE TITLE
http_mock_adapter 0.1.6 depends on older version of mockito, please upgrade.

### ISSUE THREAD

**Issue by DarkHeros09** [lomsa-dev/http-mock-adapter#89]
First thank you for creating this package,and maintaining it.

## Description

```
Because every version of http_mock_adapter depends on mockito ^4.1.3 and tdd_null_safe depends on mockito ^5.0.3, http_mock_adapter is forbidden.
```

## Steps to reproduce

1. install mockito 5.0.3
2. install http_mock_adapter 0.1.6

**Comment by GiorgiBeriashvili** [comment]
@DarkHeros09 Hi!

This issue should be fixed as of `0.2.1`.

Please let me know if there's more to do regarding the problem.

Thank you for the issue!

**Comment by DarkHeros09** [comment]
Great can't wait for it.
Ome question will i be able to use this package to test retrofit? since retrofit is using dio.

**Comment by GiorgiBeriashvili** [comment]
`0.2.1` is live just in case.

As for the testing of `retrofit`, I haven't used the package, but I took a look at it and saw that you provide an instance of `Dio` for it to work as intended, which makes me almost certain that `http_mock_adapter` can be used to mock requests made by that specific `Dio` instance.

I could be wrong but it should work just fine.

**Comment by DarkHeros09** [comment]
Thank you for your hard work 🙏, works fine now.
I'll try to provide a feedback about retrofit when i can.
