### ISSUE TITLE
Always matches when one route was matched

### ISSUE THREAD

**Issue by Albert221** [lomsa-dev/http-mock-adapter#98]
Hi! Those tests should show what's happening. The last test fails and it (IMO) shouldn't:

## Versions

* `http_mock_adapter` - `0.2.1`
* `dio` - `4.0.0`

```
Flutter 2.0.5 • channel unknown • unknown source
Framework • revision adc687823a (11 days ago) • 2021-04-16 09:40:20 -0700
Engine • revision b09f014e96
Tools • Dart 2.12.3
```

---

![image](https://user-images.githubusercontent.com/4085280/116223985-634ac980-a750-11eb-914e-8d5e1ae5b1c6.png)

```dart
import 'package:dio/dio.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:http_mock_adapter/http_mock_adapter.dart';

void main() {
  late Dio dio;
  late DioAdapter adapter;
  setUp(() {
    dio = Dio();
    adapter = DioAdapter();
    dio.httpClientAdapter = adapter;

    adapter.onGet('/test', (request) {
      request.reply(200, 'ok');
    });
  });

  test('correctly throws when does not match first request', () async {
    expectLater(
      dio.get<void>('/wont-find'),
      throwsA(isA<DioError>()),
    );
  });

  test('correctly not throws when matches first request', () async {
    expectLater(
      dio.get<void>('/test'),
      completes,
    );
  });

  test(
      'INCORRECTLY not throws when matches '
      'first request but not the next ones', () async {
    expectLater(
      dio.get<void>('/test'),
      completes,
    );

    expectLater(
      dio.get<void>('/wont-find'),
      throwsA(isA<DioError>()),
    );
  });
}

```

**Comment by theiskaa** [comment]
Hi Albert! First of all thanks for reporting/creating issue.

In your test code, I see, you are trying mocking `DioError` but you didn't created a `DioError` model and mocking function.
So you are must to mock dio before expecting.
**Your code:**
```dart
 test(
      'INCORRECTLY not throws when matches '
      'first request but not the next ones', () async {
    expectLater(
      dio.get<void>('/test'),
      completes,
    );

    expectLater(
      dio.get<void>('/wont-find'),
      throwsA(isA<DioError>()),
    );
  });
```
**But your code should be like:**
```dart
 test(
      'INCORRECTLY not throws when matches '
      'first request but not the next ones', () async {
    expectLater(dio.get<void>('/test'), completes);

    adapter.onGet("/wont-find", (request) => request.throws(404, dioError));

    expectLater(dio.get<void>('/wont-find'), throwsA(isA<DioError>()));
  });
```
And next step is creating a `DioError` model:
```dart
DioError(
      error: {'message': 'Will not find anything..'},
      requestOptions: RequestOptions(path: "/wont-find"),
      response: Response(
        statusCode: 404,
        requestOptions: RequestOptions(path: "/wont-find"),
      ),
      type: DioErrorType.response,
    );
```

However, if you want test/mock a error then you must have `DioError` model and of course mocking function of  `DioAdapter`.

## Full fixed and cleared test code: 
```dart

void main() {
  Dio dio;
  DioAdapter adapter;
  DioError dioError;

  const testPath = "/test";
  const wontFindPath = "/wont-find";

  setUp(() {
    dio = Dio();
    adapter = DioAdapter();
    dio.httpClientAdapter = adapter;

    dioError = DioError(
      error: {'message': 'Will not find anything..'},
      requestOptions: RequestOptions(path: wontFindPath),
      response: Response(
        statusCode: 404,
        requestOptions: RequestOptions(path: wontFindPath),
      ),
      type: DioErrorType.response,
    );
  });

  test('correctly throws when does not match first request', () async {
    adapter.onGet(wontFindPath, (request) => request.throws(404, dioError));
    expectLater(dio.get<void>(wontFindPath), throwsA(isA<DioError>()));
  });

  test('correctly not throws when matches first request', () async {
    adapter.onGet(testPath, (request) {
      request.reply(200, 'ok');
    });
    expectLater(dio.get<void>(testPath), completes);
  });

  test(
      'INCORRECTLY not throws when matches '
      'first request but not the next ones', () async {
    adapter.onGet(testPath, (request) {
      request.reply(200, 'ok');
    });
    
    expectLater(dio.get<void>(testPath), completes);

    adapter.onGet(wontFindPath, (request) => request.throws(404, dioError));

    expectLater(dio.get<void>(wontFindPath), throwsA(isA<DioError>()));
  });
}
```

**Comment by Albert221** [comment]
Nonono, you missed my point, sorry.

The DioError that I'm expecting is the `DioError:<DioError [DioErrorType.DEFAULT]: Assertion failed: "Could not find mocked route matching request...`. It's not anything from me.

I'm expect this exception to be thrown in my last test, because I didn't provide any `onGet` for this particular route, but it passes, when it shouldn't.

**Comment by theiskaa** [comment]
Uhmm, okay lets start from zero, what's problem you was faced? I'd explain wrong thing?

**Comment by Albert221** [comment]
1. I mock the `GET /test` response
2. I send `GET /test` request
    * It works correctly, I receive the mocked response.
3. I send `GET /wont-find` request
    * It should fail, I should receive AssertionError from `http_mock_adapter` library, because there is no such mock for that path.
    * ...but it doesn't fail. Actually, I get the response from the previously matched route.

**Comment by LukaGiorgadze** [comment]
> 1. I mock the `GET /test` response
> 2. I send `GET /test` request
>    
>    * It works correctly, I receive the mocked response.
> 3. I send `GET /wont-find` request
>    
>    * It should fail, I should receive AssertionError from `http_mock_adapter` library, because there is no such mock for that path.
>    * ...but it doesn't fail. Actually, I get the response from the previously matched route.

You will not get an error if you send a request which is not mocked, but at least you must not receive response from the previously matched route. Yeh, this makes sense.

**Comment by Albert221** [comment]
Getting an error fails the test which is something I'd want to have to see that I'm doing something wrong, maybe I wrote something wrong in tests, but maybe my business logic and/or something that I test is wrong, and this gives me value.

I stumbled upon this issue when I was checking for the header with a typo and I was surprised it was passing the tests.

**Comment by theiskaa** [comment]
Hello @Albert221 
The issue you was reported will be fixed when https://github.com/lomsa-dev/http-mock-adapter/pull/100 this PR merged.
Again thanks for reporting problem.
